name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix: 
        GOOS: [linux, windows, darwin]
        GOARCH: [amd64, 386]
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Build dedicated
      env:
        GOOS: ${{ matrix.GOOS }}
        GOARCH: ${{ matrix.GOARCH }}
        CGO_ENABLED: 0
      run: go build -o gun-dedicated-${{ matrix.GOOS }}-${{ matrix.GOARCH }} github.com/Qv2ray/gun/cmd
    - name: Upload dedicated assets
      uses: actions/upload-artifact@v2.2.1
      with:
        name: gun-dedicated-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
        path: gun-dedicated-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
    - name: Build SIP003 plugin
      env:
        GOOS: ${{ matrix.GOOS }}
        GOARCH: ${{ matrix.GOARCH }}
        CGO_ENABLED: 0
      run: go build -o gun-sip003-${{ matrix.GOOS }}-${{ matrix.GOARCH }} github.com/Qv2ray/gun/cmd/sip003
    - name: Upload SIP003 plugin assets
      uses: actions/upload-artifact@v2.2.1
      with:
        name: gun-sip003-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
        path: gun-sip003-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
